PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE m_coop_stamp(
  id INTEGER NOT NULL,
  stamp_asset_path TEXT NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO m_coop_stamp VALUES(1,'}Ni');
INSERT INTO m_coop_stamp VALUES(2,'PLI');
INSERT INTO m_coop_stamp VALUES(3,'kFS');
INSERT INTO m_coop_stamp VALUES(4,':Ni');
INSERT INTO m_coop_stamp VALUES(5,'W[P');
INSERT INTO m_coop_stamp VALUES(6,'^_"');
INSERT INTO m_coop_stamp VALUES(7,'UIO');
INSERT INTO m_coop_stamp VALUES(8,'2D7');
INSERT INTO m_coop_stamp VALUES(9,'iTu');
INSERT INTO m_coop_stamp VALUES(10,'.I:');
INSERT INTO m_coop_stamp VALUES(11,'M?{');
INSERT INTO m_coop_stamp VALUES(12,'*tb');
INSERT INTO m_coop_stamp VALUES(13,'Ww^');
INSERT INTO m_coop_stamp VALUES(14,'fU!');
INSERT INTO m_coop_stamp VALUES(15,'[RT');
INSERT INTO m_coop_stamp VALUES(16,'2`E');
INSERT INTO m_coop_stamp VALUES(17,'Om,');
INSERT INTO m_coop_stamp VALUES(18,'xNF');
INSERT INTO m_coop_stamp VALUES(19,'M[+');
INSERT INTO m_coop_stamp VALUES(20,'jl,');
INSERT INTO m_coop_stamp VALUES(21,'C}j');
INSERT INTO m_coop_stamp VALUES(22,'|T;');
INSERT INTO m_coop_stamp VALUES(23,'''hp');
INSERT INTO m_coop_stamp VALUES(24,'|eQ');
INSERT INTO m_coop_stamp VALUES(25,'elF');
INSERT INTO m_coop_stamp VALUES(26,'^g[');
INSERT INTO m_coop_stamp VALUES(27,'9a7');
INSERT INTO m_coop_stamp VALUES(28,'j*;');
INSERT INTO m_coop_stamp VALUES(29,':B(');
INSERT INTO m_coop_stamp VALUES(30,'G<Z');
INSERT INTO m_coop_stamp VALUES(31,'~-(');
INSERT INTO m_coop_stamp VALUES(32,'e!@');
INSERT INTO m_coop_stamp VALUES(33,'6xs');
INSERT INTO m_coop_stamp VALUES(34,'''=/');
INSERT INTO m_coop_stamp VALUES(35,'X:m');
INSERT INTO m_coop_stamp VALUES(36,'s4w');
INSERT INTO m_coop_stamp VALUES(37,'>dV');
INSERT INTO m_coop_stamp VALUES(38,'}2[');
INSERT INTO m_coop_stamp VALUES(39,'nS!');
INSERT INTO m_coop_stamp VALUES(40,'{~Y');
INSERT INTO m_coop_stamp VALUES(41,'Zx`');
INSERT INTO m_coop_stamp VALUES(42,'ub(');
INSERT INTO m_coop_stamp VALUES(43,'XV{');
INSERT INTO m_coop_stamp VALUES(44,'U-A');
INSERT INTO m_coop_stamp VALUES(45,'(u~');
COMMIT;
