PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE m_live_texture(
  asset_type INTEGER NOT NULL,
  asset_path TEXT NOT NULL,
  PRIMARY KEY (asset_type)
);
INSERT INTO m_live_texture VALUES(1,'gi');
INSERT INTO m_live_texture VALUES(2,'/4');
INSERT INTO m_live_texture VALUES(3,'=i');
INSERT INTO m_live_texture VALUES(4,'HD');
INSERT INTO m_live_texture VALUES(5,'-5');
INSERT INTO m_live_texture VALUES(6,'vO');
INSERT INTO m_live_texture VALUES(7,'e#');
INSERT INTO m_live_texture VALUES(8,'LQ');
INSERT INTO m_live_texture VALUES(9,'"c');
INSERT INTO m_live_texture VALUES(10,'uo');
INSERT INTO m_live_texture VALUES(11,'p%');
INSERT INTO m_live_texture VALUES(12,'_`');
INSERT INTO m_live_texture VALUES(13,'1i');
INSERT INTO m_live_texture VALUES(14,'vS');
INSERT INTO m_live_texture VALUES(15,'co');
INSERT INTO m_live_texture VALUES(16,'(''');
INSERT INTO m_live_texture VALUES(17,'Wo');
INSERT INTO m_live_texture VALUES(18,'iq');
INSERT INTO m_live_texture VALUES(19,'G*');
INSERT INTO m_live_texture VALUES(20,'ij');
INSERT INTO m_live_texture VALUES(21,'i4');
INSERT INTO m_live_texture VALUES(22,'Mc');
INSERT INTO m_live_texture VALUES(23,'G>');
INSERT INTO m_live_texture VALUES(24,'V#');
INSERT INTO m_live_texture VALUES(25,'}e');
INSERT INTO m_live_texture VALUES(26,'@');
INSERT INTO m_live_texture VALUES(27,'j/');
INSERT INTO m_live_texture VALUES(28,'38');
INSERT INTO m_live_texture VALUES(29,'lt');
INSERT INTO m_live_texture VALUES(30,'=P');
INSERT INTO m_live_texture VALUES(31,'70');
INSERT INTO m_live_texture VALUES(32,'\:');
INSERT INTO m_live_texture VALUES(33,'g6');
INSERT INTO m_live_texture VALUES(34,'}%');
INSERT INTO m_live_texture VALUES(35,'Yi');
INSERT INTO m_live_texture VALUES(36,'}/');
INSERT INTO m_live_texture VALUES(37,'o=');
INSERT INTO m_live_texture VALUES(38,'i$');
INSERT INTO m_live_texture VALUES(39,'KP');
INSERT INTO m_live_texture VALUES(40,'>\');
INSERT INTO m_live_texture VALUES(41,'\9');
INSERT INTO m_live_texture VALUES(42,'pb');
INSERT INTO m_live_texture VALUES(43,'Oy');
INSERT INTO m_live_texture VALUES(44,'K7');
INSERT INTO m_live_texture VALUES(45,'KBz');
INSERT INTO m_live_texture VALUES(46,'vAE');
INSERT INTO m_live_texture VALUES(47,'9ra');
INSERT INTO m_live_texture VALUES(48,'~xY');
INSERT INTO m_live_texture VALUES(49,'gk*');
INSERT INTO m_live_texture VALUES(50,'Ns\');
INSERT INTO m_live_texture VALUES(51,'Ojm');
INSERT INTO m_live_texture VALUES(52,'x}"');
INSERT INTO m_live_texture VALUES(53,'ydO');
INSERT INTO m_live_texture VALUES(54,'e2G');
INSERT INTO m_live_texture VALUES(55,'H4O');
COMMIT;
