PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE gacha_performance_pavement(
  asset_path TEXT NOT NULL,
  pavement TEXT NOT NULL,
  PRIMARY KEY (asset_path)
);
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_camera_01','dQ');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_cyalume_01','ee');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_cyalume_02','@0');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_cyalume_03','X?');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stage_01','zc');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stage_02','l]');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stage_03','8v');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stage_black_01','|@');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageeffect_01','IV');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageeffect_02','KC');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageeffect_03','LH');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageparticle_01','2d');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageparticle_02','~*');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_stageparticle_03','C2');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_touch_start_01','TE');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut01_touch_start_02','Cz');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_camera_01','''1');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_cyalume_01','gP');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_cyalume_02','C1');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_cyalume_03','Xt');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_stageeffect_00','mh');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_stageeffect_01','|s');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_stageeffect_02',']I');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut02_stageeffect_03','w!');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_effect_01',']}');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_01','HN');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_02','l%');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_03','_0');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_04','`/');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_05','F;');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_01','I*');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_02','Sow');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_03','y4@');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_04','Eai');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_05','6rS');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_06','KeE');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_07','G_=');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_08','1''4');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_09','n~:');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_spotlight_anchor_10','U^');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_stage_black_01','R{');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_stageeffect_01','4/');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_stageeffect_02',''';');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut03_stageeffect_03','=O');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut04_spotlight_01','f~');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut04_spotlight_02','A6');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut04_spotlight_03','_O');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut04_spotlight_04','`o');
INSERT INTO gacha_performance_pavement VALUES('fx_gacha_cut04_spotlight_05','qQ');
COMMIT;
