PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE m_movie(
  pavement TEXT NOT NULL,
  pack_name TEXT,
  PRIMARY KEY (pavement)
);
INSERT INTO m_movie VALUES('uP','npgdl6');
INSERT INTO m_movie VALUES('PX','nownac');
INSERT INTO m_movie VALUES('jn','ejlpk0');
INSERT INTO m_movie VALUES('sn','ygm3tx');
INSERT INTO m_movie VALUES('9V','wkc0n5');
INSERT INTO m_movie VALUES('zp','zyzyqq');
INSERT INTO m_movie VALUES('tp','rm6vwc');
INSERT INTO m_movie VALUES(')~','p7gpgz');
INSERT INTO m_movie VALUES('};','da3pa5');
INSERT INTO m_movie VALUES('\)','5jam6u');
INSERT INTO m_movie VALUES('Xw','5pp61r');
INSERT INTO m_movie VALUES('r','7moo81');
INSERT INTO m_movie VALUES('(@','g3ssag');
INSERT INTO m_movie VALUES('7;','kwosom');
INSERT INTO m_movie VALUES(']"','wy9o75');
INSERT INTO m_movie VALUES('hJ','bbft1o');
INSERT INTO m_movie VALUES('eX','lowini');
INSERT INTO m_movie VALUES('{n','j78ovg');
INSERT INTO m_movie VALUES('G`','8vhalw');
INSERT INTO m_movie VALUES('T<','ygseiq');
INSERT INTO m_movie VALUES('zw','azc3a1');
INSERT INTO m_movie VALUES('w;','jqljfm');
INSERT INTO m_movie VALUES('mu','y6hk1n');
INSERT INTO m_movie VALUES('u.','cd6xha');
INSERT INTO m_movie VALUES('*','h8u2le');
INSERT INTO m_movie VALUES('3(','dsg3jg');
INSERT INTO m_movie VALUES('!9','hatlw9');
INSERT INTO m_movie VALUES('T-','tcqykx');
INSERT INTO m_movie VALUES('[>','jizoo3');
INSERT INTO m_movie VALUES('xfz','uni1y0');
INSERT INTO m_movie VALUES('V''','lycicy');
INSERT INTO m_movie VALUES('_G','k5lc8b');
INSERT INTO m_movie VALUES('1nF','kfvvhp');
INSERT INTO m_movie VALUES('nf+','59ecgd');
INSERT INTO m_movie VALUES('7k','pbg6mt');
INSERT INTO m_movie VALUES('4;R','9hbwu9');
INSERT INTO m_movie VALUES('!^l','rzh93r');
INSERT INTO m_movie VALUES('_%H','p74lcv');
INSERT INTO m_movie VALUES('P0t','0gwaz5');
INSERT INTO m_movie VALUES('I;h','cxtqo2');
INSERT INTO m_movie VALUES('/CZ','l5w5ng');
INSERT INTO m_movie VALUES('bC1','5r1lom');
INSERT INTO m_movie VALUES('s~r','v1ysl9');
INSERT INTO m_movie VALUES('|o6','43b1eo');
INSERT INTO m_movie VALUES('''9(','xwzotc');
INSERT INTO m_movie VALUES('8&N','9sol1o');
INSERT INTO m_movie VALUES('o6.','l1fth3');
INSERT INTO m_movie VALUES('V|{','yb98o5');
INSERT INTO m_movie VALUES('+?{','9rsfxp');
INSERT INTO m_movie VALUES(',6.','hjmira');
INSERT INTO m_movie VALUES('ICs','yl4hnz');
INSERT INTO m_movie VALUES('64p','vvaydy');
INSERT INTO m_movie VALUES('{vb','sm0ehw');
INSERT INTO m_movie VALUES('Qv_','zfsnjj');
INSERT INTO m_movie VALUES('p&9','d9fosd');
INSERT INTO m_movie VALUES('HWl','rtoqtx');
INSERT INTO m_movie VALUES('1Fk','8kaok4');
INSERT INTO m_movie VALUES('sx?','3a9lts');
INSERT INTO m_movie VALUES('8oO','kwol8z');
COMMIT;
