PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE movie_pavement(
  asset_path TEXT NOT NULL,
  pavement TEXT NOT NULL,
  PRIMARY KEY (asset_path)
);
INSERT INTO movie_pavement VALUES('gacha_cut01_display_01','uP');
INSERT INTO movie_pavement VALUES('gacha_cut01_display_02','PX');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_01_in','jn');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_01_loop','sn');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_02_in','9V');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_02_loop','zp');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_03_in','tp');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_03_loop',')~');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_04_in','};');
INSERT INTO movie_pavement VALUES('gacha_cut03_display_04_loop','\)');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0001','Xw');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0002','r');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0003','(@');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0004','7;');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0005',']"');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0006','hJ');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0007','eX');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0008','{n');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0009','G`');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0101','T<');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0102','zw');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0103','w;');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0104','mu');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0105','u.');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0106','*');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0107','3(');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0108','!9');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0109','T-');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0201','[>');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0202','xfz');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0203','V''');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0204','_G');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0205','1nF');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0206','nf+');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0207','7k');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0208','4;R');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0209','!^l');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0210','_%H');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0211','P0t');
INSERT INTO movie_pavement VALUES('gacha_cut05_sign_ch0212','I;h');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut01_in_01','/CZ');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut01_loop_01','bC1');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut02_in_01','s~r');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut02_loop_01','|o6');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut03_in_01','''9(');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut03_loop_01','8&N');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut04_in_01','o6.');
INSERT INTO movie_pavement VALUES('mov_gve_multiresult_cut04_loop_01','V|{');
INSERT INTO movie_pavement VALUES('mov_gve_transition_in_01','+?{');
INSERT INTO movie_pavement VALUES('mov_gve_transition_loop_01',',6.');
INSERT INTO movie_pavement VALUES('mov_gve_transition_out_01','ICs');
INSERT INTO movie_pavement VALUES('mov_op_01.gl','64p');
INSERT INTO movie_pavement VALUES('mov_op_02','{vb');
INSERT INTO movie_pavement VALUES('so2997_h264','Qv_');
INSERT INTO movie_pavement VALUES('so2997_prime','p&9');
INSERT INTO movie_pavement VALUES('so2998_h264','HWl');
INSERT INTO movie_pavement VALUES('so2998_prime','1Fk');
INSERT INTO movie_pavement VALUES('so2999_h264','sx?');
INSERT INTO movie_pavement VALUES('so2999_prime','8oO');
COMMIT;
