PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE shader_pavement(
  asset_path TEXT NOT NULL,
  pavement TEXT NOT NULL,
  PRIMARY KEY (asset_path)
);
INSERT INTO shader_pavement VALUES('_asdepth.shader','§&*<');
INSERT INTO shader_pavement VALUES('_asmemberdepth.shader','§U7h');
INSERT INTO shader_pavement VALUES('_asmemberdepthprop.shader','§^vG');
INSERT INTO shader_pavement VALUES('_asmembermain.shader','§7`2');
INSERT INTO shader_pavement VALUES('_asmembermainprop.shader','§|GB');
INSERT INTO shader_pavement VALUES('_asmemberoutline.shader','§H#5');
INSERT INTO shader_pavement VALUES('_asmemberoutlineprop.shader','§''o3');
INSERT INTO shader_pavement VALUES('asblendadditiveopaque.shader','§+YK');
INSERT INTO shader_pavement VALUES('asblendopaque.shader','§/ye');
INSERT INTO shader_pavement VALUES('asclothfragopaque.shader','§2!;');
INSERT INTO shader_pavement VALUES('asclothvertopaque.shader','§/V^');
INSERT INTO shader_pavement VALUES('ascoloringadditiveblendopaque.shader','§T:e');
INSERT INTO shader_pavement VALUES('ascoloringopaque.shader','§X#f');
INSERT INTO shader_pavement VALUES('ascoloringtexturetransparent.shader','§M~:');
INSERT INTO shader_pavement VALUES('ascoloringtransparent.shader','§j-"');
INSERT INTO shader_pavement VALUES('ascoloropaque.shader','§auN');
INSERT INTO shader_pavement VALUES('asemissiveopaque.shader','§ocm');
INSERT INTO shader_pavement VALUES('asflashlight.shader','§&~%');
INSERT INTO shader_pavement VALUES('asgeneralopaque.shader','§Etf');
INSERT INTO shader_pavement VALUES('asgeneraltransparent.shader','§<NQ');
INSERT INTO shader_pavement VALUES('asgeneraltransparentcutout.shader','§/rl');
INSERT INTO shader_pavement VALUES('asgeneraltransparentuvscroll.shader','§^,k');
INSERT INTO shader_pavement VALUES('aslive.shadervariants','§w5W');
INSERT INTO shader_pavement VALUES('asliveso0009.shadervariants','§?9Y');
INSERT INTO shader_pavement VALUES('asliveso0036.shadervariants','§:!P');
INSERT INTO shader_pavement VALUES('asliveso1005.shadervariants','§.iM');
INSERT INTO shader_pavement VALUES('asliveso1025.shadervariants','§cR)');
INSERT INTO shader_pavement VALUES('asliveso1079.shadervariants','§^G2');
INSERT INTO shader_pavement VALUES('asliveso2028.shadervariants','§+nv');
INSERT INTO shader_pavement VALUES('asliveso2030.shadervariants','§>Os');
INSERT INTO shader_pavement VALUES('asmatcapopaque.shader','§g~S');
INSERT INTO shader_pavement VALUES('asmatcaptransparent.shader','§fvM');
INSERT INTO shader_pavement VALUES('asmember.shader','§E2u');
INSERT INTO shader_pavement VALUES('asmemberprop.shader','§Lxt');
INSERT INTO shader_pavement VALUES('asnavi.shadervariants','§6U0');
INSERT INTO shader_pavement VALUES('aspenlight.shader','§oj6');
INSERT INTO shader_pavement VALUES('aspenlightlegacy.shader','§^Hy');
INSERT INTO shader_pavement VALUES('aspropdecalopaque.shader','§FHg');
INSERT INTO shader_pavement VALUES('asrimlightopaque.shader','§VT)');
INSERT INTO shader_pavement VALUES('assmoke.shader','§}>\');
INSERT INTO shader_pavement VALUES('asso0009highqualitytrail.shader','§}h+');
INSERT INTO shader_pavement VALUES('asso0009lowqualitytrail.shader','§.GL');
INSERT INTO shader_pavement VALUES('asso0036flag.shader','§d3A');
INSERT INTO shader_pavement VALUES('asso1005displaywavetexture.shader','§nau');
INSERT INTO shader_pavement VALUES('asso1025flag.shader','§gX|');
INSERT INTO shader_pavement VALUES('asso1079butterfly.shader','§U,$');
INSERT INTO shader_pavement VALUES('asso2028butterfly.shader','§`0T');
INSERT INTO shader_pavement VALUES('asso2030displaywavetexture.shader','§g0/');
INSERT INTO shader_pavement VALUES('assoftparticle.shader','§B|l');
INSERT INTO shader_pavement VALUES('assoftparticlebillboard.shader','§b|<');
INSERT INTO shader_pavement VALUES('asstage.shader','§g<b');
INSERT INTO shader_pavement VALUES('aswaterproceduraltransparent.shader','§Xql');
INSERT INTO shader_pavement VALUES('aswatersurface.shader','§HsQ');
INSERT INTO shader_pavement VALUES('aswipemask.shader','§<^5');
COMMIT;
