PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE skill_timeline_pavement(
  asset_path TEXT NOT NULL,
  pavement TEXT NOT NULL,
  PRIMARY KEY (asset_path)
);
INSERT INTO skill_timeline_pavement VALUES('duo_2000_001.timeline.asset','K&a');
INSERT INTO skill_timeline_pavement VALUES('duo_2000_002.timeline.asset','~^L');
INSERT INTO skill_timeline_pavement VALUES('duo_2000_003.timeline.asset','U^D');
INSERT INTO skill_timeline_pavement VALUES('sol_0001_001.timeline.asset','^''6');
INSERT INTO skill_timeline_pavement VALUES('sol_0002_001.timeline.asset',')S5');
INSERT INTO skill_timeline_pavement VALUES('sol_0003_001.timeline.asset','BN(');
INSERT INTO skill_timeline_pavement VALUES('sol_0004_001.timeline.asset','gWi');
INSERT INTO skill_timeline_pavement VALUES('sol_0005_001.timeline.asset','p~Z');
INSERT INTO skill_timeline_pavement VALUES('sol_0006_001.timeline.asset','#l"');
INSERT INTO skill_timeline_pavement VALUES('sol_0007_001.timeline.asset','zZm');
INSERT INTO skill_timeline_pavement VALUES('sol_0008_001.timeline.asset','AdP');
INSERT INTO skill_timeline_pavement VALUES('sol_0009_001.timeline.asset','dXs');
INSERT INTO skill_timeline_pavement VALUES('sol_0101_001.timeline.asset','[xg');
INSERT INTO skill_timeline_pavement VALUES('sol_0102_001.timeline.asset','.T4');
INSERT INTO skill_timeline_pavement VALUES('sol_0103_001.timeline.asset','uFm');
INSERT INTO skill_timeline_pavement VALUES('sol_0104_001.timeline.asset','vQ:');
INSERT INTO skill_timeline_pavement VALUES('sol_0105_001.timeline.asset','mq.');
INSERT INTO skill_timeline_pavement VALUES('sol_0106_001.timeline.asset','zv{');
INSERT INTO skill_timeline_pavement VALUES('sol_0107_001.timeline.asset','iVM');
INSERT INTO skill_timeline_pavement VALUES('sol_0108_001.timeline.asset','P^!');
INSERT INTO skill_timeline_pavement VALUES('sol_0109_001.timeline.asset','[6v');
INSERT INTO skill_timeline_pavement VALUES('sol_0201_001.timeline.asset','.pB');
INSERT INTO skill_timeline_pavement VALUES('sol_0202_001.timeline.asset','aLy');
INSERT INTO skill_timeline_pavement VALUES('sol_0203_001.timeline.asset','rM[');
INSERT INTO skill_timeline_pavement VALUES('sol_0204_001.timeline.asset','m/=');
INSERT INTO skill_timeline_pavement VALUES('sol_0205_001.timeline.asset','f|)');
INSERT INTO skill_timeline_pavement VALUES('sol_0206_001.timeline.asset','eRn');
INSERT INTO skill_timeline_pavement VALUES('sol_0207_001.timeline.asset','Pz/');
INSERT INTO skill_timeline_pavement VALUES('sol_0208_001.timeline.asset','G<$');
INSERT INTO skill_timeline_pavement VALUES('sol_0209_001.timeline.asset','`7u');
INSERT INTO skill_timeline_pavement VALUES('sol_0210_001.timeline.asset','[iy');
INSERT INTO skill_timeline_pavement VALUES('sol_0211_001.timeline.asset','""9');
INSERT INTO skill_timeline_pavement VALUES('sol_0212_001.timeline.asset','ydL');
INSERT INTO skill_timeline_pavement VALUES('tri_2000_001.timeline.asset','ah)');
INSERT INTO skill_timeline_pavement VALUES('tri_2000_002.timeline.asset','Hp[');
INSERT INTO skill_timeline_pavement VALUES('tri_2000_003.timeline.asset','i+^');
INSERT INTO skill_timeline_pavement VALUES('uni_0001_001.timeline.asset','>dI');
INSERT INTO skill_timeline_pavement VALUES('uni_0002_001.timeline.asset',';un');
INSERT INTO skill_timeline_pavement VALUES('uni_0003_001.timeline.asset','tL?');
INSERT INTO skill_timeline_pavement VALUES('uni_0101_001.timeline.asset','Mma');
INSERT INTO skill_timeline_pavement VALUES('uni_0102_001.timeline.asset','6Zu');
INSERT INTO skill_timeline_pavement VALUES('uni_0103_001.timeline.asset','CaQ');
INSERT INTO skill_timeline_pavement VALUES('uni_0201_001.timeline.asset','>k#');
INSERT INTO skill_timeline_pavement VALUES('uni_0202_001.timeline.asset','MID');
INSERT INTO skill_timeline_pavement VALUES('uni_0203_001.timeline.asset','8A=');
INSERT INTO skill_timeline_pavement VALUES('uni_0204_001.timeline.asset','.cZ');
COMMIT;
